"""
Static market data for 7 sectors — updated manually 1x/month.
Based on BPS data, market research, and UMKM analysis for Indonesia 2024.
"""

SECTOR_STATIC_DATA = {
    "fashion": {
        "market_size_label": "Rp 198,7 T",
        "yoy_growth": 6.2,
        "umkm_share": 65,
        "top_subsectors": [
            "Baju Muslim",
            "Batik & Tenun Tradisional",
            "Streetwear Lokal",
            "Aksesori Fashion",
        ],
        "peak_months": [3, 4, 8, 12],
        "context": "Industri tekstil & pakaian di Indonesia tersegmentasi antara fast fashion import dan UMKM lokal yang berkembang pesat, terutama di kategori modest wear dan traditional patterns.",
        "quarter": "Q3 2024",
        "icon": "fa-shirt",
        "color_accent": "#F0C855",
    },
    "beauty": {
        "market_size_label": "Rp 87,3 T",
        "yoy_growth": 12.4,
        "umkm_share": 58,
        "top_subsectors": [
            "Skincare Natural Lokal",
            "Makeup Halal-Sertifikasi",
            "Perawatan Rambut Organik",
            "Supplement Kecantikan",
        ],
        "peak_months": [1, 5, 10, 11],
        "context": "Pasar kosmetik Indonesia tumbuh cepat didorong oleh preferensi lokal terhadap skincare halal, natural ingredients, dan brand lokal yang certified eco-friendly.",
        "quarter": "Q3 2024",
        "icon": "fa-sparkles",
        "color_accent": "#FF69B4",
    },
    "fnb": {
        "market_size_label": "Rp 312,5 T",
        "yoy_growth": 8.7,
        "umkm_share": 72,
        "top_subsectors": [
            "Kuliner Rumahan (cloud kitchen)",
            "Makanan Sehat & Diet",
            "Makanan Tradisional Premium",
            "Beverage & Minuman Sehat",
        ],
        "peak_months": [2, 4, 7, 12],
        "context": "FnB adalah sektor terbesar dengan dominasi UMKM. Pertumbuhan didorong cloud kitchen, healthy food trend, dan momen tradisional (lebaran, nataru).",
        "quarter": "Q3 2024",
        "icon": "fa-utensils",
        "color_accent": "#FFB347",
    },
    "gadget": {
        "market_size_label": "Rp 156,2 T",
        "yoy_growth": 4.8,
        "umkm_share": 22,
        "top_subsectors": [
            "Accessories Smartphone",
            "Tech Gadgets Niche",
            "Electronis Gaming",
            "Smart Home Devices",
        ],
        "peak_months": [1, 6, 11, 12],
        "context": "Sektor gadget didominasi importer besar, namun UMKM berkembang di niche accessories dan smart home solutions. Kompetisi tinggi dari marketplace.",
        "quarter": "Q3 2024",
        "icon": "fa-mobile-screen-button",
        "color_accent": "#448AFF",
    },
    "home": {
        "market_size_label": "Rp 124,8 T",
        "yoy_growth": 5.3,
        "umkm_share": 61,
        "top_subsectors": [
            "Furniture Minimalis Lokal",
            "Dekorasi Rumah Interior",
            "Peralatan Dapur Inovatif",
            "Tekstil Rumah Tangga",
        ],
        "peak_months": [2, 3, 6, 9],
        "context": "Home & Living berkembang seiring tren renovasi rumah dan interior design DIY. UMKM lokal kompetitif di furniture custom dan dekorasi affordable.",
        "quarter": "Q3 2024",
        "icon": "fa-house-chimney",
        "color_accent": "#9C7C5C",
    },
    "hobi": {
        "market_size_label": "Rp 68,4 T",
        "yoy_growth": 9.1,
        "umkm_share": 51,
        "top_subsectors": [
            "Peralatan Olahraga Lokal",
            "Travel & Adventure Gear",
            "Gaming & Hobi Niche",
            "Fitness & Wellness Equipment",
        ],
        "peak_months": [1, 5, 7, 10],
        "context": "Hobi & Lifestyle tumbuh dari meningkatnya kesadaran health & wellness, lifestyle content, dan community-driven shopping di kalangan millennial.",
        "quarter": "Q3 2024",
        "icon": "fa-star",
        "color_accent": "#FFD700",
    },
    "musiman": {
        "market_size_label": "Rp 215,6 T*",
        "yoy_growth": 28.5,
        "umkm_share": 70,
        "top_subsectors": [
            "Hampers Lebaran & Nataru",
            "Kue & Snack Tradisional",
            "Fashion Pesta & Perayaan",
            "Gift Sets Musiman",
        ],
        "peak_months": [2, 3, 4, 12],
        "context": "Sektor musiman booming saat Lebaran dan Tahun Baru dengan lonjakan hingga 3x lipat. UMKM mendominasi dengan produk tradisional dan customizable gifts.",
        "quarter": "Q3 2024",
        "icon": "fa-calendar-day",
        "color_accent": "#FF6B6B",
    },
}
